### PR TITLE
adding README.md

### PR DESCRIPTION
**Pull request by sanchita141011**

### CODE REVIEW

**Comment by 9inpachi** [comment]
Hi,

Be sure to check the commit and pull request conventions and update the
things. They should be somewhere in the dev guide.

TL:DR Commit messages should mention the related Jira issue (create one if
it doesn't exist).

**Comment by vmassol** [comment]
> Be sure to check the commit and pull request conventions and update the
things. They should be somewhere in the dev guide.
>
> TL:DR Commit messages should mention the related Jira issue (create one if
it doesn't exist).

@9inpachi yes you're right except for this case ;) ie pure dev commits. See the jira rules at https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HJIRABestPractices (it's rule 2: `Rule: Don't create unnecessary issues`).

**Comment by 9inpachi** [comment]
@vmassol yeah, cool. Thanks for pointing out. ;)
But I remember most devs add a `Misc:` prefix when there was no Jira issue. I guess that's not an enforced convention.

**Comment by vmassol** [comment]
> But I remember most devs add a Misc: prefix when there was no Jira issue. I guess that's not an enforced convention.

Indeed, we haven't formalized this in the doc yet but we could. It's not as important as having the jira issue number for user-related issues though.

**Comment by tmortagne** [comment]
We tend to do that a lot on xwiki-commons/xwiki-rendering/xwiki-platform but on my side it's more a tradition and I don't really see any benefit to it and don't use that in other projects.

**Comment by 9inpachi** [comment]
@vmassol There seems to be an issue on Jira for this [XAWS-1](https://jira.xwiki.org/browse/XAWS-1) so it should indeed follow the commit conventions since the issue mentions README as well.

**Comment by vmassol** [comment]
So https://jira.xwiki.org/browse/XAWS-1 is not following the process defined since it's not put in a "Development Issue Only" component. See https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HJIRABestPractices

@sachin10101998 could you check and add the missing component (you're the lead of the jira project so you have the permissions normally).

What's important is to not have XAWS-1 in the release notes when excluding "Development Issue Only" since users of this extension will not care at all about XAWS-1 and thus they shouldn't see that in the Release Notes.

**Comment by 9inpachi** [comment]
Correct me if I am wrong but essentially the practice applies to the GitHub commits and PRs since there is an issue (dev or not).

**Comment by sachin10101998** [comment]
The corresponding JIRA issue was created to have a list of tasks for students to work upon before starting actual GSoC to get them familiar with workflow they'll need to follow once the program starts. i.e. create JIRA Issue corresponding to the work you are doing and describe why it's needed, create PR with the JIRA Issue number in commit message , get ite merged and close the issue and follow the standard protocols for writing code for XWiki projects. I'll add the "Development issues only" component while creating such pre requisite tasks . Thanks for the sharing the relevant documentation @vmassol .

**Pull request closed without merging**
